name: Dependabot auto-merge
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ !contains(steps.metadata.outputs.dependency-names, '@bshgroup/component') &&
                !contains(steps.metadata.outputs.dependency-names, '@bshgroup/footer-header') &&
                steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}